# AUTOGENERATED FROM 'app/queries/create_todo.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateTodoResult(NoPydanticValidation):
    id: uuid.UUID
    title: str


async def create_todo(
    executor: edgedb.AsyncIOExecutor,
    *,
    title: str,
) -> CreateTodoResult:
    return await executor.query_single(
        """\
        with title:= <str>$title,
             todo:= (insert Todo {title:=title})
        select todo {id, title};\
        """,
        title=title,
    )
